export const REGISTER_SUCCESS ='REGISTER_SUCCESS';
export const CHECK_SUCCESS = 'CHECK_SUCCESS';
export const REGISTER_FAIL = 'CHECK_FAIL';
export const CHECK_FAIL = 'LOGIN_FAIL';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SEARCH_USERS = 'SEARCH_USERS';
export const SET_LOADING = 'SET_LOADING';
export const CLEAR_USERS = 'CLEAR_USERS';
export const GET_USER = 'GET_USER';